Added events when fade-in/fade-out are complete
naudio/NAudio pull request #1136
Opened 2024-03-15 01:26 UTC by SMSapereAude

According to `FadeInOutSampleProvider` docs:

>The `FadeInOutSampleProvider` is a very basic fade provider, and you may want additional features like:
>
>- automatically fading out when you reach the end of the source
>- automatically stopping at the end of a fade out
>- cross-fading into another input. 

These two events might be helpful for implementing such features.
It's also a contribution from our project, for the NAudio community ;)

2024-03-15 01:42 UTC, SMSapereAude commented
@markheath Hi, could you please take a look at this PR?

2024-12-30 02:16 UTC, nightblade9 commented
Merged into [Sonic Boom 1.1.0](https://github.com/nightblade9/SonicBoom/releases/tag/v1.1.0), which is a fork of NAudio. Thank you for your contribution!

2025-05-13 14:28 UTC, trolleycrash requested changes
The final contribution to make this PR complete would be to demonstrate how it's used in `FadeInOutDemo`

2025-05-13 14:28 UTC, trolleycrash commented on NAudio.Core/Wave/SampleProviders/FadeInOutSampleProvider.cs
>                      ClearBuffer(buffer, sample + offset, sourceSamplesRead - sample);
I feel like the event should be fired after the buffer is cleared for the following reasons:


1. Consistent State: When the event handler executes, the audio sample buffer will be in its final state with zeroed samples at the end.
2. Error Handling: If clearing the buffer were to somehow fail, we wouldn't want to falsely signal completion.
3. Logical Flow: The event signals the completion of the entire fade-out process, which includes the buffer clearing step.

2025-09-07 22:08 UTC, fsa-SM commented
Hi, sorry for long time of absence (devices which were used to access my account were unfortunately seized.)
This pull request can be closed as I don't have means to push changes related to requested changes.

2025-09-07 22:12 UTC, SMSapereAude2 commented on NAudio.Core/Wave/SampleProviders/FadeInOutSampleProvider.cs
>                      ClearBuffer(buffer, sample + offset, sourceSamplesRead - sample);
I agree. If event handler execution takes longer time than buffer can keep NAudio busy (tens of milliseconds), then NAudio will have stutter effect. Will be fixed with next PR.

2026-07-01 12:46 UTC, markheath commented
thanks for this contribution. I've implemented it against the main branch

2026-07-01 12:46 UTC, closed without merging